apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  hostNetwork: true
  containers:
    - image: clusterregistry.azurecr.io/frontend:1.0
      name: frontend-container
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      livenessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3

