apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    app: database
spec:
  hostNetwork: true
  volumes:
    - name: db-persistent-volume
      persistentVolumeClaim:
        claimName: db-persistent-volume-claim
  containers:
    - image: postgres:alpine3.20
      name: db-container
      env:
        - name: POSTGRES_PASSWORD
          value: "pokemon"
      ports:
          - containerPort: 5432
            name: http
            protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-persistent-volume
      livenessProbe:
        tcpSocket:
          port: 5432
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3