apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim
spec:
  storageClassName: nginx-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi