apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-persistent-volume
spec:
  storageClassName: nginx-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/persistent-volume"